version: "3"

services:
  print-server:
    build: 
      context: .
      dockerfile: ./.docker/easy-rch-printf-print-server.dockerfile
    environment:
      NATS_URL: nats://nats:4222
      NATS_STREAM_NAME: TEST
      NATS_SUBJECT: test
      RCH_PRINTF_URL: http://localhost:9000
    depends_on: 
      - nats

  nats:
    image: nats
    ports: 
      - 4222:4222
      - 8222:8222
    command: "--store_dir /datastore --jetstream"
    volumes:
      - nats_data:/datastore

# networks: 

volumes:
  nats_data:
